from io_fate_mdl.util import *

MATERIAL_STANDARD = 0
MATERIAL_PREALPHA = 1
MATERIAL_ALPHA = 2
MATERIAL_SHADOW = 3
MATERIAL_REFLECT = 4
MATERIAL_STATICCUBEMAP = 5
MATERIAL_ILLUMINATION = 6
MATERIAL_MULTIPLY = 7
MATERIAL_NORMALMAP = 8 
MATERIAL_SPHEREMAP = 9
MATERIAL_REFLECTPOST = 10
MATERIAL_STATICCUBEMAPPOST = 11
MATERIAL_SPHEREMAPPOST = 12
MATERIAL_TYPES = 13

